-- Database: meetuphub

-- DROP DATABASE IF EXISTS meetuphub;
CREATE TABLE users (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

CREATE TABLE categories (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    PRIMARY KEY(id)
);

CREATE TABLE events (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(255),
    start_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    location_id INTEGER,
    organizer_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY(id)
);
CREATE TABLE event_category_mapping (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY(id),
    UNIQUE (event_id, category_id)
);

CREATE TABLE locations (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE event_participants (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(255),
    PRIMARY KEY(id),
    UNIQUE (user_id, event_id)
);

CREATE TABLE location_category_mapping (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY(id),
    UNIQUE (location_id, category_id)
);


CREATE TABLE tags (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    tag_name TEXT NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE event_tag_mapping (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY(id),
    UNIQUE (event_id, tag_id)
);



CREATE TABLE roles (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE user_roles (
    id INTEGER NOT NULL UNIQUE GENERATED ALWAYS AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY(id),
    UNIQUE (user_id, role_id)
);
